import type { Metadata } from 'next'
import './globals.css'
import { Sidebar } from '@/components/Sidebar'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className='antialiased'>
      <body >
        <div className='min-h-screen grid grid-cols-app bg-white'>
          <Sidebar/>
          <main className='px-8 pb-12 pt-8'> {children}</main> 
        </div>
      </body>
    </html>
  )
}
